2025-09-09T20:13:08-04:00 | ai_error | {"err":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sitiosnuevos_hospital.doctores' doesn't exist"}
2025-09-09T20:14:16-04:00 | ai_error | {"err":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sitiosnuevos_hospital.doctores' doesn't exist"}
2025-09-09T20:14:16-04:00 | ai_error | {"err":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sitiosnuevos_hospital.doctores' doesn't exist"}
2025-09-09T20:14:16-04:00 | ai_error | {"err":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sitiosnuevos_hospital.doctores' doesn't exist"}
2025-09-09T20:14:22-04:00 | ai_error | {"err":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sitiosnuevos_hospital.doctores' doesn't exist"}
2025-09-09T20:27:20-04:00 | ai_safe | {"input":[],"out":{"ok":true,"via":"safe","campos":[],"mensajes":[]}}
2025-09-09T20:29:10-04:00 | openai_json_fail | {"err":"HTTP 429"}
2025-09-09T20:29:10-04:00 | ai_safe | {"input":{"texto":"Paciente Luis Zambrano colelap dr pablo veliz ","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":["OpenAI no respondió o clave ausente; usando heurística."]}}
2025-09-09T20:31:21-04:00 | openai_json_fail | {"err":"HTTP 429"}
2025-09-09T20:31:21-04:00 | ai_safe | {"input":{"texto":"paciente luis zambrano hora de cirugia (10: am ingreso 8:00 am no encesita laboratorio arco en c si dr pablo veliz fractura de humero","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":["OpenAI no respondió o clave ausente; usando heurística."]}}
2025-09-09T20:33:25-04:00 | openai_json_fail | {"err":"HTTP 429"}
2025-09-09T20:33:25-04:00 | ai_safe | {"input":{"texto":"paciente luis zambrano hora de cirugia (10: am ingreso 8:00 am no encesita laboratorio arco en c si dr pablo veliz fractura de humero","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":["OpenAI no respondió o clave ausente; usando heurística."]}}
2025-09-09T20:35:35-04:00 | openai_json_fail | {"err":"HTTP 429"}
2025-09-09T20:35:35-04:00 | ai_safe | {"input":{"texto":"Paciente Luis Zambrano","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":["OpenAI no respondió o clave ausente; usando heurística."]}}
2025-09-09T20:36:33-04:00 | openai_json_fail | {"err":"HTTP 429"}
2025-09-09T20:36:33-04:00 | ai_safe | {"input":{"texto":"Paciente Luis Zambrano","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":["OpenAI no respondió o clave ausente; usando heurística."]}}
2025-09-09T20:37:25-04:00 | openai_json_fail | {"err":"HTTP 429"}
2025-09-09T20:37:25-04:00 | ai_safe | {"input":{"texto":"Paciente Luis Zambrano","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":["OpenAI no respondió o clave ausente; usando heurística."]}}
2025-09-09T20:53:32-04:00 | ai_safe | {"input":{"texto":"paciente luis zambrano","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T20:54:06-04:00 | ai_safe | {"input":{"texto":"colelap luis zambrano dr layedra","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T20:55:25-04:00 | ai_safe | {"input":{"texto":"colelap luis zambrano dr layedra","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T20:57:46-04:00 | ai_safe | {"input":{"texto":"Paciente Juan Pérez, 56 años; artroscopia de rodilla; Dr. Rivera Toala; sala 1; 09:00.","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T21:03:03-04:00 | ai_safe | {"input":{"texto":"Paciente Juan Pérez, 56 años; artroscopia de rodilla; Dr. Rivera; sala 1; 09:00.","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T21:03:11-04:00 | ai_safe | {"input":{"texto":"Paciente Juan Pérez, 56 años; artroscopia de rodilla; Dr. Rivera; sala 1; 09:00.","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T21:05:00-04:00 | ai_safe | {"input":{"texto":"Paciente Juan Pérez, 56 años; artroscopia de rodilla; Dr. Rivera; sala 1; 09:00.","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T21:05:09-04:00 | ai_safe | {"input":{"texto":"\nPaciente Juan Pérez, 56 años; artroscopia de rodilla; Dr. Rivera; sala 1; 09:00.\n🩺 Riesgo estimado: BAJO","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T21:06:12-04:00 | ai_safe | {"input":{"texto":"Paciente Juan Pérez, 56 años; artroscopia de rodilla; Dr. Rivera; sala 1; 09:00.","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T21:06:27-04:00 | ai_safe | {"input":{"texto":"Paciente Juan Pérez, 56 años; artroscopia de rodilla; Dr. Rivera; sala 1; 09:00.","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T21:06:35-04:00 | ai_safe | {"input":{"texto":"Paciente Juan Pérez, 56 años; artroscopia de rodilla; Dr. Rivera; sala 1; 09:00. sangrando","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T21:06:45-04:00 | ai_safe | {"input":{"texto":"Paciente Juan Pérez, 56 años; artroscopia de rodilla; Dr. Rivera; sala 1; 09:00. sangrando emergencia","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"safe","campos":{"riesgo_estimado":"MEDIO"},"mensajes":[]}}
2025-09-09T21:10:14-04:00 | ai_safe_error | {"err":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hora_inicio' in 'SELECT'"}
2025-09-09T21:11:32-04:00 | ai_safe_error | {"err":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hora_inicio' in 'SELECT'"}
2025-09-09T21:13:37-04:00 | ai_safe_error | {"err":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hora_inicio' in 'SELECT'"}
2025-09-09T21:17:49-04:00 | ai_safe | {"input":{"texto":"Paciente Ana Torres, 45 años; artroscopia de rodilla; Dr. Rivera; sala 1; 09:00.","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"openai_json","campos":{"paciente":"Ana Torres","edad":45,"procedimiento":"ARTROSCOPIA DE RODILLA","cirujano":"Dr. Rivera","cirujano_id":42,"habitación":"sala 1","fecha":null,"hora_inicio":"09:00","hora_fin":null,"duracion_min_estimada":90,"riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T21:19:14-04:00 | ai_safe | {"input":{"texto":"Paciente luis zambrano dr layedra anestsiolog dr trae su equipo hora de ingreso 8:00 am hora de cirugia 7:00 pm laboratorios tp y tpt y ekg arco en C no","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"openai_json","campos":{"paciente":"Luis Zambrano","edad":null,"procedimiento":null,"cirujano":"Dr. Layedra","cirujano_id":235,"habitación":null,"fecha":null,"hora_inicio":"8:00 am","hora_fin":"7:00 pm","riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T21:19:47-04:00 | ai_safe | {"input":{"texto":"Paciente luis zambrano dr layedra anestsiolog dr trae su equipo hora de ingreso 8:00  hora de cirugia 17:00 laboratorios tp y tpt y ekg arco en C no","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"openai_json","campos":{"paciente":"Luis Zambrano","edad":null,"procedimiento":"COLUMNA","cirujano":"Dr. Layedra","cirujano_id":235,"habitación":"C","fecha":null,"hora_inicio":"8:00","hora_fin":"17:00","duracion_min_estimada":150,"riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T21:20:15-04:00 | ai_safe | {"input":{"texto":"Paciente luis zambrano dr layedra anestsiolog dr trae su equipo hora de ingreso 08:00  hora de cirugia 17:00 laboratorios tp y tpt y ekg arco en C no","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"openai_json","campos":{"paciente":"Luis Zambrano","edad":null,"procedimiento":null,"cirujano":"Dr. Layedra","cirujano_id":235,"habitación":null,"fecha":null,"hora_inicio":"08:00","hora_fin":"17:00","riesgo_estimado":"BAJO"},"mensajes":[]}}
2025-09-09T21:20:39-04:00 | ai_safe | {"input":{"texto":"Paciente luis zambrano dr layedra anestsiolog dr trae su equipo hora de ingreso 08:00  hora de cirugia 17:00 laboratorios tp y tpt y ekg arco en C no","fecha":"","sala":"","hora_inicio":"","hora_fin":""},"out":{"ok":true,"via":"openai_json","campos":{"paciente":"Luis Zambrano","edad":null,"procedimiento":null,"cirujano":"Dr. Layedra","cirujano_id":235,"habitación":null,"fecha":null,"hora_inicio":"08:00","hora_fin":"17:00","riesgo_estimado":"BAJO"},"mensajes":[]}}
